# -*- coding: utf-8 -*-
"""DAY 1ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZryuxnAG6i8Touplesd3jsOfiWyrjGi
"""

import numpy as np
import random as random

a=np.random.randint(10,50,(5,3))
a

a[2:4:,0:2]

